### PR TITLE
Optimize MixedHistogramUserDefined

### PR DESCRIPTION
**Pull request by jschueller**
I've rewritten MixedHistogramUserDefined without using Mixture (I kept the asMixture method)
Perf is >360x faster for the pdf in dim 10.

cc @regislebrun

@phwuil can we merge your branch ? I'd like to cleanup the useless OT namespaces in .cxx files, and I dont want to conflict with your work.

### CODE REVIEW

**Comment by regislebrun** [comment]
Could you please publish your bench? I see room for improvement in the getRealization() method and would like to check the idea. Otherwise, good job!

**Comment by jschueller** [comment]
see the end of the python test of MixedHistogramUserDefined I only benchmarked pdf & cdf.

**Comment by regislebrun** [comment]
I have implemented a new version of getRealization() based on DistFunc::rDiscrete() instead of UserDefined::getRealization(). On the following test-case the creation time drops from 0.097s to 0.0085s and the sampling rate raises from 1130000rng/s to 1930000rng/s:
```
import otagrum
import openturns as ot
from time import time

ticksCollection = [[0.0, 1.0, 3.0, 6.0], [1.0, 2.0, 3.0], [0.0, 1.0, 3.0, 6.0], [1.0, 2.0, 3.0], [0.0, 1.0, 3.0, 6.0], [1.0, 2.0, 3.0], [0.0, 1.0, 3.0, 6.0], [1.0, 2.0, 3.0], [0.0, 1.0, 3.0, 6.0], [1.0, 2.0, 3.0]]
kind = [1, 0]*5
probabilityTable = ot.RandomGenerator.Generate(3**10)
t0 = time()
distribution = otagrum.MixedHistogramUserDefined(ticksCollection, kind, probabilityTable)
distribution.setDescription(['A', 'B']*5)
t1 = time()
print("Creation=", t1 - t0, "s")
size = 100000000
t0 = time()
distribution.getSample(size)
t1 = time()
print("speed=", size / (t1 - t0), "rng/s")
```

[code.zip](https://github.com/openturns/otagrum/files/3398297/code.zip)

**Comment by jschueller** [comment]
note that this can be also done in Mixture

**Comment by regislebrun** [comment]
If you do that, StandardDistributionPoylnomialFactory will no be able to construct the orthonormal polynomial family of a Mixture. So don't do that!

**Comment by jschueller** [comment]
@regislebrun I applied your patch, I can merge this PR if you want

**Pull request merged**
